name: Deploy med cypress tester test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          start: npm run startwithmock
          wait-on: http://localhost:3000
      - name: debug
        run: |
          ls cypress/screenshots/test_spec.js
          pwd
      - name: last opp bilde
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -F 'file=@/home/runner/work/taga/taga/cypress/screenshots/test_spec.js/Test test -- Test 1.png' -F "initial_comment=Shakes the cat" -F "channels=paw-cypress-test" -H "${SLACK_TOKEN}" https://slack.com/api/files.upload

  build:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: true
